### ISSUE TITLE
Benchmarks!

### ISSUE THREAD

**Issue by lulf** [seedwing-io/seedwing-policy#12]
I'd like to add some benchmarks to the engine. If we intend to be a serious alternative for real-time use cases, it needs to be fast so we need to know how fast it is. Also feels like a good way to learn about how the engine works for me personally.

**Comment by bobmcwhirter** [comment]
Some things to benchmark:

* "compilation" times when building the policy system (e.g, booting up the server).
* Evaluation of the types that don't involve I/O.
* Evaluation of functions that do involve I/O or complex processing.

**Comment by lulf** [comment]
I will create some basic patterns in Rego and Dogma and compare
