### ISSUE TITLE
Deterministic ordering of evaluation tree

### ISSUE THREAD

**Issue by lulf** [seedwing-io/seedwing-policy#15]
One thing I noticed writing the initial benchmarks was that the Builder::finish() would vary a lot even for pure in-memory functions. I tried to print the entire datastructure in two separate runs and diff them, and it looks like the order of evaluation can vary, which might be a contributing factor.

I can take a look at fixing it, but wanted to check if you think it's worth it? Deterministic latency on evaluation I think would be a good thing.

**Comment by bobmcwhirter** [comment]
In theory it should not matter, but yah, world holds a HashMap which will vary in ordering.

When evaluating, we do a O(1) lookup (or whatever) in the HashMap, and then roll from the found Type (ahem, Pattern) directly, not involving the World beyond that.

Also, I'm assuming lir::World (which I'm moving around a bit). Do you mean any other world?

I defer to whatever solution you think is necessary.

**Comment by lulf** [comment]
I tried replacing all HashMaps with IndexMap, and it did seem to lower then upper bound and reduce variance, but not as much as I was hoping for.
