### ISSUE TITLE
Should we support YAML request/responses?

### ISSUE THREAD

**Issue by jcrossley3** [seedwing-io/seedwing-policy#64]

**Comment by bobmcwhirter** [comment]
Yes

**Comment by lulf** [comment]
Would anyone use it? I think this feature would be mostly unused, and opens up the rest API to all the ambiguities of yaml.

**Comment by bobmcwhirter** [comment]
Was thinking Kube folks might enjoy yaml.

**Comment by lulf** [comment]
Does Kube support YAML in the REST API?  I thought it only supported JSON and Protobuf/GRPC serialization formats, but converting to those in the CLI tool talking to the API.

**Comment by bobmcwhirter** [comment]
I dunno. I only read memes, I don't actually use Kube. 

I defer to y'all who know better.

**Comment by bobmcwhirter** [comment]
We should stub a page of docs about formats.
