### ISSUE TITLE
Evaluate and represent rego policies from hacbs

### ISSUE THREAD

**Issue by lulf** [seedwing-io/seedwing-policy#78]
Look at the policies in https://github.com/hacbs-contract/ec-policies/ and translate them to seedwing policies to find feature gaps in seedwing and potential improvements.

#### Notes/Documentation:
* [seedwing/hacbs-dogma-policies](https://github.com/danbev/hacbs-dogma-policies)
* [seedwing/hacbs-dogma-policies#missing features](https://github.com/danbev/hacbs-dogma-policies#missing-features)

**Comment by danbev** [comment]
> and translate them to seedwing policies

Just to clarify this before I start: 
Should this task actually rewrite all their policy rules in Dogma to determine this, or should this task do a visual inspection of their rules and see if there is anything sticks out that might not be possible write in Dogma yet?

**Comment by lulf** [comment]
I think the latter. Having some kind of overview of the different policy rules allow us to make better decisions on which rules fit the seedwing primary use cases too so we can focus on that.

**Comment by danbev** [comment]
@lulf I've updated this  issues description and added a link to the possible [missing features](https://github.com/danbev/hacbs-dogma-policies#missing-features). 
Do you think we can consider this issue as done, and perhaps open new issues for any of these features that we think we should implement (now or later)?

**Comment by lulf** [comment]
Awsome work! I think all of the functions makes sense, both on list and string. In dogma, there are no arrays, just lists, which have some of these operations.

The rule metadata is something that doesn't exist yet, but iirc we've discussed it, and it would be a good addition.

**Comment by lulf** [comment]
We can close this issue, I think it's all captured in your doc. Creating new issues for the missing features makes sense.
