### ISSUE TITLE
Expose statistics and metrics as prometheus endpoint on the server

### ISSUE THREAD

**Issue by lulf** [seedwing-io/seedwing-policy#90]
Existing stats, but also generic http request stats. This allows aggregating statistics when running multiple instances of the server as well.

**Comment by bobmcwhirter** [comment]
I tried looking at Prometheus exporters, but good lort, that's a lot of docs that don't really tell me what I need to expose.

Unless my Google-fu is just bad. Do you have a link as to wtf I should make available and which format?

**Comment by lulf** [comment]
I can look into this, but I think the way to go is to use the https://docs.rs/prometheus/latest/prometheus/ crate to create a metrics registry, and register a metric per 'pattern'.

**Comment by bobmcwhirter** [comment]
Ah good call
